//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 10:31:52 PM CEST 
//


package com.company.xsdschemas.invoiceitem;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.company.xsdschemas.invoice.InvoiceRequest;


/**
 * <p>Java class for invoiceItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="invoiceItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ordinate" type="{http://com/xsdSchemas/types}ordinate3"/>
 *         &lt;element name="merchandiseOrServiceName" type="{http://com/xsdSchemas/types}str120"/>
 *         &lt;element name="amount" type="{http://com/xsdSchemas/types}dec10_2"/>
 *         &lt;element name="unit" type="{http://com/xsdSchemas/types}str6"/>
 *         &lt;element name="unitPrice" type="{http://com/xsdSchemas/types}dec10_2"/>
 *         &lt;element name="value" type="{http://com/xsdSchemas/types}dec12_2"/>
 *         &lt;element name="discountPercentage" type="{http://com/xsdSchemas/types}dec5_2"/>
 *         &lt;element name="disounctAmount" type="{http://com/xsdSchemas/types}dec12_2"/>
 *         &lt;element name="discountTaken" type="{http://com/xsdSchemas/types}dec12_2"/>
 *         &lt;element name="totalTaxes" type="{http://com/xsdSchemas/types}dec12_2"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "invoiceItem", propOrder = {
    "ordinate",
    "merchandiseOrServiceName",
    "amount",
    "unit",
    "unitPrice",
    "value",
    "discountPercentage",
    "disounctAmount",
    "discountTaken",
    "totalTaxes"
})
@Entity
public class InvoiceItem {
	
	@Id
	@GeneratedValue
	private Long id;
	
	@Column(nullable = false)
	@XmlElement(required = true)
    protected short ordinate;
	
	@Column(nullable = false)
    @XmlElement(required = true)
    protected String merchandiseOrServiceName;
    
	@Column(nullable = false)
    @XmlElement(required = true)
    protected BigDecimal amount;
    
	@Column(nullable = false)
    @XmlElement(required = true)
    protected String unit;
    
	@Column(nullable = false)
    @XmlElement(required = true)
    protected BigDecimal unitPrice;
    
	@Column(nullable = false)
    @XmlElement(required = true)
    protected BigDecimal value;
    
	@Column(nullable = false)
    @XmlElement(required = true)
    protected BigDecimal discountPercentage;
    
	@Column(nullable = false)
    @XmlElement(required = true)
    protected BigDecimal disounctAmount;
    
	@Column(nullable = false)
    @XmlElement(required = true)
    protected BigDecimal discountTaken;
    
	@Column(nullable = false)
    @XmlElement(required = true)
    protected BigDecimal totalTaxes;
	
	@ManyToOne(optional = false)
	private InvoiceRequest invoice;

    /**
     * Gets the value of the ordinate property.
     * 
     */
    public short getOrdinate() {
        return ordinate;
    }

    /**
     * Sets the value of the ordinate property.
     * 
     */
    public void setOrdinate(short value) {
        this.ordinate = value;
    }

    /**
     * Gets the value of the merchandiseOrServiceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchandiseOrServiceName() {
        return merchandiseOrServiceName;
    }

    /**
     * Sets the value of the merchandiseOrServiceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchandiseOrServiceName(String value) {
        this.merchandiseOrServiceName = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnit(String value) {
        this.unit = value;
    }

    /**
     * Gets the value of the unitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * Sets the value of the unitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUnitPrice(BigDecimal value) {
        this.unitPrice = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValue(BigDecimal value) {
        this.value = value;
    }

    /**
     * Gets the value of the discountPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiscountPercentage() {
        return discountPercentage;
    }

    /**
     * Sets the value of the discountPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiscountPercentage(BigDecimal value) {
        this.discountPercentage = value;
    }

    /**
     * Gets the value of the disounctAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDisounctAmount() {
        return disounctAmount;
    }

    /**
     * Sets the value of the disounctAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDisounctAmount(BigDecimal value) {
        this.disounctAmount = value;
    }

    /**
     * Gets the value of the discountTaken property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiscountTaken() {
        return discountTaken;
    }

    /**
     * Sets the value of the discountTaken property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiscountTaken(BigDecimal value) {
        this.discountTaken = value;
    }

    /**
     * Gets the value of the totalTaxes property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalTaxes() {
        return totalTaxes;
    }

    /**
     * Sets the value of the totalTaxes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalTaxes(BigDecimal value) {
        this.totalTaxes = value;
    }
    
    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public InvoiceRequest getInvoice() {
		return invoice;
	}

	public void setInvoice(InvoiceRequest invoice) {
		this.invoice = invoice;
	}
}
