//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 11:37:44 PM CEST 
//


package com.company.wsdl;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="accountNumber" type="{http://com/xsdSchemas/types}accountNumber"/&gt;
 *         &lt;element name="requestDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="sectionOrdinate" type="{http://com/xsdSchemas/types}ordinate2"/&gt;
 *         &lt;element name="previousBalance" type="{http://com/xsdSchemas/types}dec15_2"/&gt;
 *         &lt;element name="numberOfChangesProfit" type="{http://com/xsdSchemas/types}num6"/&gt;
 *         &lt;element name="totalProfit" type="{http://com/xsdSchemas/types}dec15_2"/&gt;
 *         &lt;element name="numberOfChangesDue" type="{http://com/xsdSchemas/types}num6"/&gt;
 *         &lt;element name="totalDue" type="{http://com/xsdSchemas/types}dec15_2"/&gt;
 *         &lt;element name="currentBalance" type="{http://com/xsdSchemas/types}dec15_2"/&gt;
 *         &lt;element name="accountStatementSectionItems" type="{http://com/xsdSchemas/accountStatementSectionItem}accountStatementSectionItem" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accountNumber",
    "requestDate",
    "sectionOrdinate",
    "previousBalance",
    "numberOfChangesProfit",
    "totalProfit",
    "numberOfChangesDue",
    "totalDue",
    "currentBalance",
    "accountStatementSectionItems"
})
@XmlRootElement(name = "accountStatementSectionResponse")
public class AccountStatementSectionResponse {

    @XmlElement(required = true)
    protected String accountNumber;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar requestDate;
    @XmlElement(required = true)
    protected short sectionOrdinate;
    @XmlElement(required = true)
    protected BigDecimal previousBalance;
    @XmlElement(required = true)
    protected BigInteger numberOfChangesProfit;
    @XmlElement(required = true)
    protected BigDecimal totalProfit;
    @XmlElement(required = true)
    protected BigInteger numberOfChangesDue;
    @XmlElement(required = true)
    protected BigDecimal totalDue;
    @XmlElement(required = true)
    protected BigDecimal currentBalance;
    @XmlElement(required = true)
    protected List<AccountStatementSectionItem> accountStatementSectionItems;

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the requestDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRequestDate() {
        return requestDate;
    }

    /**
     * Sets the value of the requestDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRequestDate(XMLGregorianCalendar value) {
        this.requestDate = value;
    }

    /**
     * Gets the value of the sectionOrdinate property.
     * 
     */
    public short getSectionOrdinate() {
        return sectionOrdinate;
    }

    /**
     * Sets the value of the sectionOrdinate property.
     * 
     */
    public void setSectionOrdinate(short value) {
        this.sectionOrdinate = value;
    }

    /**
     * Gets the value of the previousBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPreviousBalance() {
        return previousBalance;
    }

    /**
     * Sets the value of the previousBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPreviousBalance(BigDecimal value) {
        this.previousBalance = value;
    }

    /**
     * Gets the value of the numberOfChangesProfit property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfChangesProfit() {
        return numberOfChangesProfit;
    }

    /**
     * Sets the value of the numberOfChangesProfit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfChangesProfit(BigInteger value) {
        this.numberOfChangesProfit = value;
    }

    /**
     * Gets the value of the totalProfit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalProfit() {
        return totalProfit;
    }

    /**
     * Sets the value of the totalProfit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalProfit(BigDecimal value) {
        this.totalProfit = value;
    }

    /**
     * Gets the value of the numberOfChangesDue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfChangesDue() {
        return numberOfChangesDue;
    }

    /**
     * Sets the value of the numberOfChangesDue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfChangesDue(BigInteger value) {
        this.numberOfChangesDue = value;
    }

    /**
     * Gets the value of the totalDue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalDue() {
        return totalDue;
    }

    /**
     * Sets the value of the totalDue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalDue(BigDecimal value) {
        this.totalDue = value;
    }

    /**
     * Gets the value of the currentBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurrentBalance() {
        return currentBalance;
    }

    /**
     * Sets the value of the currentBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurrentBalance(BigDecimal value) {
        this.currentBalance = value;
    }

    /**
     * Gets the value of the accountStatementSectionItems property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accountStatementSectionItems property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccountStatementSectionItems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccountStatementSectionItem }
     * 
     * 
     */
    public List<AccountStatementSectionItem> getAccountStatementSectionItems() {
        if (accountStatementSectionItems == null) {
            accountStatementSectionItems = new ArrayList<AccountStatementSectionItem>();
        }
        return this.accountStatementSectionItems;
    }

}
